dofile('rbxasset://coreguiscripts\\MainBotChatScript.lua')
dofile('rbxasset://coreguiscripts\\Resizer.lua')
dofile('rbxasset://coreguiscripts\\SettingsScript.lua')
dofile('rbxasset://coreguiscripts\\StarterScript.lua')
dofile('rbxasset://coreguiscripts\\SubMenuBuilder.lua')
dofile('rbxasset://coreguiscripts\\ToolTipper.lua')